version: "3.3"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forcebridge
    ports:
      - 3306:3306
  ckb:
    image: tockb/ckb-dev:v0.39.2
    ports:
      - "8114:8114"
  ckb-indexer:
    image: tockb/ckb-indexer:ab57116
    ports:
      - "8116:8116"
    environment:
      - RUST_LOG=info
    command: ckb-indexer -s /tmp/ckb-indexer-test -c http://ckb:8114 -l 0.0.0.0:8116
    depends_on:
      - ckb
  geth:
    image: tockb/geth-priv:v1.9.23
    volumes:
      - type: volume
        source: geth-dag
        target: /root/.ethash
      - type: bind
        source: ./geth
        target: /config
    ports:
      - "8545:8545"
  btc:
    image: tockb/btc-regtest
    stdin_open: true
    tty: true
    ports:
      - "18443:18443"
  eos:
    image: tockb/eosio-priv:2.0.11
    ports:
      - '8888:8888'
volumes:
  geth-dag:
